// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqtkmqlibkcszvljlqtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxdGttcWxpYmtjc3p2bGpscXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODI1MTcsImV4cCI6MjA3MTM1ODUxN30.-HdTOLvP-w91KVSKXS2o9mJFxxzMKpch5sxifAE6qvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});